### ISSUE TITLE
Lint PHP syntax workflow

### ISSUE THREAD

**Issue by Potherca** [novoserve/github-workflows#10]

**Comment by MarcHagen** [comment]
Please review https://github.com/novoserve/cloudrack/pull/200 for now.
As you probably have a better understanding of github actions than me, we can figure-out how we merge/move this to a reusable workflow :) 

I have created a image for various testing tools within 1 container. I use the same concept for my own personal Gitlab.
https://github.com/novoserve/docker-workflow-php

**Comment by Potherca** [comment]
Although I can understand the desire to have one action check multiple things, it is not something I am a fan of... On failure, an extra step is needed in order to see which tools has failed. (Rather than just knowing by the job name). Of course, this can still be achieved with an all-in-one environment, just with a single tool enabled per job (rather than per step).

For an all-in-one environment, it is worth looking into https://github.com/shivammathur/setup-php, which comes with [a lot of tools](https://github.com/shivammathur/setup-php#wrench-tools-support) already installed. To give an idea of how this might work (as a regular workflow):

```yml
---
on: [push, pull_request]

jobs:
  lint-php-syntax:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: ["7.2", "7.3","7.4", "8.0", "8.1"]

    name: "Lint PHP ${{ matrix.php }} Syntax"

    steps:
      - uses: actions/checkout@v3

      # Use specific PHP versions (and tools)
      # @see https://github.com/shivammathur/setup-php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          tools: parallel-lint

      - name: Lint PHP for parse errors
        run: parallel-lint -e php --exclude vendor --exclude .git --checkstyle --no-progress .
```

<details><summary>Or as a re-usable workflow</summary>

```yaml
---
on:
  workflow_call:
    inputs:
      # inputs.versions: >- ["7.2", "7.3","7.4", "8.0", "8.1"]
      versions:
        default: >-
          ["7.2", "7.3","7.4", "8.0", "8.1"]
        description: Stringified JSON object listing target versions
        required: false
        type: string

jobs:
  lint-php-syntax:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: ${{ fromJson(inputs.versions) }}

    name: "Lint PHP ${{ matrix.php }} Syntax"

    steps:
      - uses: actions/checkout@v3

      # Use specific PHP versions (and tools)
      # @see https://github.com/shivammathur/setup-php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          tools: parallel-lint

      - name: Lint PHP for parse errors
        run: parallel-lint -e php --exclude vendor --exclude .git --checkstyle --no-progress .
```

</details>
