### ISSUE TITLE
Lint shell workflow (shellcheck)

### ISSUE THREAD

**Issue by Potherca** [novoserve/github-workflows#2]

**Comment by MarcHagen** [comment]
Maybe adding https://github.com/koalaman/shellcheck for this.
https://github.com/fearphage/shellcheck-action

**Comment by Potherca** [comment]
Rather than using all sorts of different vendors for each check, I've been inclined to use pipeline-components for all vendors.

What I have for this, thus far is:


```yml
---
on:
  workflow_call:
    inputs:
      # inputs.files: "**/*.sh"
      files:
        default: "**/*.sh"
        description: 'String: Files to lint'
        required: false
        type: string
      # inputs.format: gcc
      format:
        default: gcc
        description: 'String: output format to use (checkstyle, diff, gcc, json, json1, quiet, tty)'
        required: false
        type: string

jobs:
  lint-shell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # Grab default config if local config does not exist
      # ShellCheck will look for `.shellcheckrc` and `shellcheckrc`
      - if: hashFiles( '.shellcheckrc', 'shellcheckrc' ) == ''
        name: Fetch default config
        run: >
          wget 
          https://raw.githubusercontent.com/novoserve/github-workflows/main/config/shellcheckrc
          -O '.shellcheckrc'

      - name: Lint shell files
        env:
          PIPELINECOMPONENTS_GLOBASSIST: true
        uses: pipeline-components/shellcheck@v0.11.1
        with:
          directory: ${{ inputs.files }}
          options: --format=${{ inputs.format }}
```
